name: Build and Publish LLVM toolchain image
on:
  pull_request:
    paths:
      - Dockerfile
      - .github/workflows/toolchain.yml
  push:
    tags: [ "v*" ]
    paths:
      - Dockerfile
      - .github/workflows/toolchain.yml
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      # Free up disk space on Github-hosted runner
      - name: Disk usage
        run: df -h
      - uses: jlumbroso/free-disk-space@v1.3.1
        with:
          android: true
          dotnet: true
          haskell: true
          large-packages: true

      - name: Disk usage after freeing up space
        run: df -h

      # Actually build the Docker container
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: GHCR Log-in
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/xdslproject/llvm
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch

      - name: Build and push
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
